
MDB_NODES = 3
NETWORK_PREFIX = "192.168.15."

Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = false
    config.hostmanager.manage_guest = true
    config.vm.box = "ubuntu/bionic64"
    (1..MDB_NODES).each do |i|
        config.vm.define "mongodb-node-#{i}" do |node|
            node.vm.network "private_network", ip: NETWORK_PREFIX + "#{i + 100}"
            node.vm.provision :shell, :path => "scripts/install_utilities.sh", :args => "#{MDB_NODES} #{i}"
            node.vm.provision :shell, :path => "scripts/install_mongodb.sh", :args => "#{MDB_NODES} #{i}"
            #node.vm.provision :reload
            node.vm.provision "shell", inline: "echo 'Node mongodb-node-#{i} is up and running!'"
            node.vm.hostname = "mongodb-node-#{i}"
            node.vm.provider :virtualbox do |vb|
                vb.name = "mongodb-node-#{i}"
            end
        end
    end  

    config.vm.provider "virtualbox" do |v|
        #  This setting controls how much cpu time a virtual CPU can use. A value of 50 implies a single virtual CPU can use up to 50% of a single host CPU.
        # v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
        v.cpus = 1
        v.memory = "1024"
    end

end   